### ISSUE TITLE
Implement new EventAPI from Slack 

### ISSUE THREAD

**Issue by pid42** [BenTheElder/slack-rs#124]
I'm currently working on a slack bot and decided do use rust for that. 
I found this crate (the the slack-api also) and decided to use them as most of the message formats are already handled. 
But, I'm currently using EventAPI instead of RTM. 
I would like to contribute that work back, but I do have some questions:

- should both be kept in slack-rs crate, or you think it would be better to keep it separate ?
- if kept together (what I think would be  better), would it be possible to move the current rtm into a mod, and having eventapi in another ? (that would break existing code, and I don't know how stable should the api be kept). 
- also, slack-rs exposes slack-api as sync, but the Implementation I'm using for EventAPI uses tokio/warp , so if the user uses the slack-api exposed from slack-rs instead of directly, it crashes. 

Is there any communication channel with one of the maintainers of the repo ?

**Comment by dten** [comment]
Hey. I'm not that familiar with how the event system works.

I'm tempted to say it would be better split up. It could be a feature in this crate though if there's an advantage. I would guess that not many people would use both rtm and events. Probably one or the other.

I would say it's unnecessary to move the rtm stuff but I can see why you'd want to.

**Comment by pid42** [comment]
EventAPI supposelly replaces RTM api for several cases, but:
- it's push based (you expose and endpoint and slack pushes events to you)
- its more granular (you control which events are sent to you)

Why would be nice to be a feature:
- most of the events are shared between both apis, what changes is how we receive the events (endpoint or websocket)

I mentioned moving so we make explicit that its a RTM implementation, now that Slack have two different apis. That would me it more explicit. 
being a feature would be very nice , the users could select which type of connection they want to use (or both, as its also a valid case mentioned in slack documentation)

Also, currently Slack documentation recommends using EventAPI instead of RTM.

**Comment by dten** [comment]
I would be cautious about sharing the event types. Given the inconsistency of Slack's other types I'd expect that the two APIs provide very similar but annoyingly different data. And they also seem likely to diverge.

I think it makes sense as a feature so wouldn't be apposed, but I do think features suck for discoverability, and it becomes hazey what the dependencies are though.

Unless there's a huge amount to share I think crate sounds most sensible, and we can always pull out a crate to share. I think the main shared bit might be event types but I already think caution there is advised for that.

**Comment by pid42** [comment]
Well, documentation states that the events are identical, except that they are wrapped in a wrapper event in eventapi. I think it's safe to assume that we can rely on that, so, sharing the events would be nice.
We could break the events in a separate library and have slack-rtm and slack-eventapi use it, instead of the features.
But, using both at the same time is a described use case scenario at the documentation, so, I guess exposing as features would be better.

**Comment by dten** [comment]
Okay sounds convincing enough :D

**Comment by Kinrany** [comment]
> most of the events are shared between both apis, what changes is how we receive the events (endpoint or websocket)

A better option may be extracting the shared events into a new crate. This will also help replacing the event types later when the APIs start to diverge.

Edit: or is this the reason `slack_api` exists?
