### ISSUE TITLE
Bug on missing "color" field.

### ISSUE THREAD

**Issue by BenTheElder** [BenTheElder/slack-rs#22]
Unfortunately i'm out of time for now, but there appears to be a rather bad bug in `0.10.1`:

main.rs
````
extern crate slack;

struct SlackRtmHandler;

impl slack::EventHandler for SlackRtmHandler {
	fn on_receive(&mut self, cli: &mut slack::RtmClient, json_str: &str){
		println!("Received: {}", json_str.to_string());
	}

	fn on_ping(&mut self, cli: &mut slack::RtmClient){
		println!("<on_ping>");
	}

	fn on_close(&mut self, cli: &mut slack::RtmClient){
		println!("<on_close>");
	}

	fn on_connect(&mut self, cli: &mut slack::RtmClient){
		println!("<on_connect>");
	}
}

fn main() {
	let mut handler = SlackRtmHandler;
	let slack_key = std::env::var("SLACK_KEY").unwrap();
	let mut slack_client = slack::RtmClient::new(&slack_key);
	slack_client.login_and_run(&mut handler).unwrap();
}
````
running gives:
````
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: JsonDecode(MissingFieldError("color"))', src/libcore/result.rs:732
````

**Comment by BenTheElder** [comment]
cc @mthjones

**Comment by BenTheElder** [comment]
Also happens when running the example. Should have done that before running out `0.10.1`.
Happens right after login. My guess is it fails to decode the "hello" event.

**Comment by BenTheElder** [comment]
Want to fix this bug so after finishing taking care of some other stuff.... here is a Quick "diagnosis":
````
[benjamin@Benjamins-MacBook-Pro: ~/dev/slack-rs]
$ grep -R color ./src
./src/api/message_events.rs:                    "color": "#36a64f",
./src/api/message_events.rs:                assert_eq!(attachments.unwrap()[0].color.as_ref().unwrap(), "#36a64f");
./src/api/message_events.rs:                    "color": "D0D0D0",
./src/api/message_events.rs:                assert_eq!(attachments.unwrap()[0].color.as_ref().unwrap(), "D0D0D0");
./src/api/rtm.rs:                    "color": "9f69e7",
./src/api/types.rs:    pub color: String,
./src/api/types.rs:    pub color: Option<String>,
./src/api/users.rs:                "color": "9f69e7",
./src/api/users.rs:                    "color": "9f69e7",
./src/api/users.rs:                    "color": "9f69e7",
````
The only non-`Option` `"color"` field is in the `types::User` struct.

Changing that to an `Option<String>` fixes it locally. I'm going to push a fix now.

**Comment by mthjones** [comment]
Sorry about that! I never ran into that during my own testing. The user types always had a color for me. Unfortunately, I think we'll likely end up finding a few more of these. I'm so tempted to just wrap every field in Option, since there's not really any solid documentation on what is and isn't always included.

Also, because Slack's API isn't versioned, this library can and probably will break at any time and there's nothing we can do to prevent that. :(

**Comment by BenTheElder** [comment]
No worries, I don't think anyone else, was using 0.10.X yet
All we can do to prevent breakage is test away and make sure semver stays
accurate. For now I'm working on a new project using it so I can test it
more.

I don't think we should wrap every field with option, it'd be ugly to parse
something and get {None, None, ... None}.
