### ISSUE TITLE
slack::error::Error is not a Rust std::error::Error

### ISSUE THREAD

**Issue by mthjones** [BenTheElder/slack-rs#24]
Ran into this issue today when trying to return a `Result<_, Box<std::error::Error>>` today (being lazy and not writing my own error wrapper). The slack error just needs to [`impl std::error::Error`](https://doc.rust-lang.org/std/error/trait.Error.html).

I'll submit a PR for this in a bit.

**Comment by BenTheElder** [comment]
I'll keep my eye out for the PR, this'll be a good addition.
