### ISSUE TITLE
upgrade hyper and openssl

### ISSUE THREAD

**Issue by durka** [BenTheElder/slack-rs#27]
A lot of stuff depends on hyper 0.7, so it would be nice to support those without causing version conflicts. It looks like there were breaking changes in `openssl::ssl::Ssltream` so it isn't just a super easy Cargo.toml change.

**Comment by durka** [comment]
It looks like websocket also needs to be upgraded, because slack-rs depends on an old version of websocket which has wildcard dependencies. But it's a more invasive change because websocket 0.13.2 introduced lifetime parameters :(

**Comment by BenTheElder** [comment]
I'll take a look at it tonight. I'm done with finals now and was just looking into rust 1.5, still no (stable) way to catch panics it seems, so upgrading the openssl crate is a priority.

**Comment by BenTheElder** [comment]
Finally got to it, some things came up, on the devel branch it was simply a Cargo.toml change. I'm going to go ahead and merge devel into master soon.

**Comment by BenTheElder** [comment]
Closed via https://github.com/BenTheElder/slack-rs/issues/28

The crates.io package should be out shortly.
