### ISSUE TITLE
Does not reconnect on network drop / pickup

### ISSUE THREAD

**Issue by dten** [BenTheElder/slack-rs#30]
Are we supposed to handle this ourself?

**Comment by BenTheElder** [comment]
Yes. You could handle this in on_close in your handler.

**Comment by dten** [comment]
on_close is never fired. After connecting, i switch laptop to flightmode, wait up to a minute or two and nothing happens. Switch flightmode off and nothing happens also, but the bot never gets any more messages.
I see this on Ubuntu and Windows 10 by the way

**Comment by BenTheElder** [comment]
Odd.
Well if on_close isn't firing then that's a different bug that needs
fixing. I'll try to look into that later today, can you open an issue for
that with a bug report?

Incidentally the reconnect in on_close method should work, I have a pet
project that does that.  Slack will periodically intentionally disconnect
clients cleanly for EG server switch. I'm guessing that the connection just
hangs when you go into flight mode. In that case perhaps a timeout on the
web socket will work.

**Comment by BenTheElder** [comment]
closing in favor of https://github.com/BenTheElder/slack-rs/issues/31
