### ISSUE TITLE
the example always return "invalid channel id" 

### ISSUE THREAD

**Issue by piaoger** [BenTheElder/slack-rs#35]
error message:
on_event(event: Err(JsonDecode(MissingFieldError("type"))), raw_json: "{\"ok\":false,\"reply_to\":0,\"error\":{\"code\":0,\"msg\":\"invalid channel id\"}}")

**Comment by BenTheElder** [comment]
Does the slack team associated with the api key you are using have a `#general` channel?

**Comment by piaoger** [comment]
Thank you.

There is a #general channel is the team. I added a new bot user and create a new RtmClient with api token for the bot.
However, in bot configuration page, I found my bot is in no channels. I am still new to slack and not  sure why. Do you have any suggestions?

**Comment by BenTheElder** [comment]
It's been a while since I created a fresh bot integration, but I think sending `/invite @bot_name` in `#general` may be the solution.

**Comment by BenTheElder** [comment]
I've just tested, and even with an offline bot, sending `/remove @bot_name` and then `/invite @bot_name` removed and added the bot to `#general` in my test group.

**Comment by BenTheElder** [comment]
If that solves your problem then I'll add a note to the readme.

**Comment by piaoger** [comment]
Yes, it works :)

 "/invite @botname" resolved the issue and I can even see "<@U0LMWUZFD|botname> has joined the channel" in realtime response.

**Comment by BenTheElder** [comment]
Excellent.
