### ISSUE TITLE
Message replies cause `JsonDecode` errors due to missing `type` field

### ISSUE THREAD

**Issue by squidpickles** [BenTheElder/slack-rs#36]
When a message is sent to Slack, it replies with a confirmation containing an `ok` boolean and a `reply_to` corresponding to the send message's id, but it does not have a `type` field.

The missing `type` field causes problems in the `decode` method, where event type is matched on that field.

It seems that either the library could:
- fully track success/failure of sent messages, using the `id` and `reply_to` fields, and calling back to the `EventHandler`, or
- send blind notifications to the `EventHandler` via callback, so it can do any desired message tracking. (Seems harder for the user, if much easier for the lib developer, unless it's doing its own message id generation)
- Ignore those messages altogether

(See "Sending Messages" in https://api.slack.com/rtm)

**Comment by BenTheElder** [comment]
I do not actively work with slack bots myself anymore, but I believe this
is I believe the previous behavior was that the message was ignored.

I'm not sure what the ideal api for this would be,  but I think tracking
success / failure would be useful to the user.

**Comment by BenTheElder** [comment]
Without changing the current api _too_ much we could have an event passed to event handler with the "type" being something like  `Response`, and have the `id` returned from the `send_message` result.

Alternatively, like you said we could do tracking within the library, but we'd still need to communicate back to the user which message failed / succeeded.

I'm leaning towards the former as it seems like the least breaking change, but I think something like supplying an optional failure / success callback when sending a message might be easier for the user.

**Comment by squidpickles** [comment]
The former keeps the library a little bit more lightweight (no data storage, the messiness of callbacks), so it sounds good. I'm happy to work on that when I have some spare time.

**Comment by BenTheElder** [comment]
Ok, thanks! I'm pretty buried in other work at the moment but if you don't
get to it I will eventually.

**Comment by squidpickles** [comment]
Fixed in commit 3cc8d43.
