### ISSUE TITLE
send_message with unescaped characters in message fails to send

### ISSUE THREAD

**Issue by mthjones** [BenTheElder/slack-rs#8]
I noticed this bug when trying to send a message that contained a debug-formatted `Vec<String>`. The debug printed value is something like `{"val1", "val2"}`, which is inserted directly into the message json sent with `send_message`.

Actual output:
`{"id": 1,"type": "message", "channel": "id","text": "{"val1", "val2"}"}`

Expected output:
`{"id": 1,"type": "message", "channel": "id","text": "{\"val1\", \"val2\"}"}`

This isn't limited to quotation marks and will happen with any character that should be escaped (e.g. `\`). 

`serde_json` has an [`escape_str`](https://serde-rs.github.io/json/serde_json/ser/fn.escape_str.html) that could come in handy here. I don't mind sending a PR with a fix if there's no issue pulling in a `serde_json` dependency!

**Comment by BenTheElder** [comment]
I have a fix for that coming out now, thanks!

BTW: I will be switching to serde_json once custom_derive is stable.

**Comment by BenTheElder** [comment]
Hopefully 0.8.2 should solve this, I've just published it and yanked 0.8.1

I'm surprised I didn't run into this sooner, I wonder if there's a good way to do rust tests against the slack api...

**Comment by mthjones** [comment]
It works! Thanks for the quick fix.

I think in this case, just testing that the json is valid for a number of scenarios would be good (e.g. when string contains quote, contains backslash, is empty, etc.). Testing against the slack API itself would be difficult, but unit testing against the Slack specs shouldn't be too bad (though I say that with no Rust testing experience!).

**Comment by BenTheElder** [comment]
YW, I'm not using rust very much yet but I intend to keep this maintained.

I'll try to get some tests out in the next update, I generally just test it
against a small slack group I have with some friends right now.
